# -*- coding: utf-8 -*-
"""IRS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYTBz-w1IS2M19w372jv0HBvF4QlcM7_
"""

from collections import defaultdict
documents = {
    "D1": "information retrieval system",
    "D2": "retrieval model in information retrieval",
    "D3": "information system"
}
inverted_index = defaultdict(list)

for doc_id, text in documents.items():
    words = text.lower().split()

    for word in set(words):
        inverted_index[word].append(doc_id)
print("Inverted Index:\n")
for term, docs in sorted(inverted_index.items()):
    print(f"{term} -> {docs}")

from collections import defaultdict
import re

with open("documents.txt", "r", encoding="utf-8") as f:
    content = f.read()

documents = {}
for doc in content.strip().split("\n\n"):
    doc_id, text = doc.split(":", 1)
    documents[doc_id.strip()] = text.strip().lower()

inverted_index = defaultdict(list)

for doc_id, text in documents.items():
    words = re.findall(r'\w+', text)

    for word in set(words):
        inverted_index[word].append(doc_id)

for term, docs in sorted(inverted_index.items()):
    print(f"{term} -> {docs}")

