# -*- coding: utf-8 -*-
"""IRS3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POgePYZr0nrZo3sAPlfS9_FaPDY5E3Mm
"""

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Download resources (run once)
nltk.download('stopwords')

# Sample DataFrame
df = pd.DataFrame({
    'Text': [
        'Students are studying in the college and playing games',
        'The cat is sitting on the mat'
    ]
})

# Stop words and stemmer
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

# Function for preprocessing
def preprocess(text):
    words = text.split()

    # Stop Word Removal
    filtered = [word for word in words if word.lower() not in stop_words]

    # Stemming
    stemmed = [ps.stem(word) for word in filtered]

    return " ".join(stemmed)

# Apply preprocessing
df['Processed_Text'] = df['Text'].apply(preprocess)

print(df)

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Download stopwords (run once)
nltk.download('stopwords')

# Read document line by line
df = pd.read_csv("document.txt", header=None, names=["Text"])

# Initialize stopwords and stemmer
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

# Preprocessing function
def preprocess(text):
    words = text.split()

    # Remove stop words
    filtered_words = [word for word in words
                      if word.lower() not in stop_words]

    # Apply stemming
    stemmed_words = [ps.stem(word) for word in filtered_words]

    return " ".join(stemmed_words)

# Process document
df["Processed_Text"] = df["Text"].apply(preprocess)

print(df)