# -*- coding: utf-8 -*-
"""IRS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_ysmIugdDOCDMkrECEFGR4XHsTKsrj1
"""

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
train = fetch_20newsgroups(subset='train')
test = fetch_20newsgroups(subset='test')

# TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(train.data)
X_test = vectorizer.transform(test.data)

# Naive Bayes
model = MultinomialNB()
model.fit(X_train, train.target)

# Prediction
pred = model.predict(X_test)

# Results
print("Accuracy:", accuracy_score(test.target, pred))
print("\nClassification Report:\n")
print(classification_report(test.target, pred,
                            target_names=test.target_names))

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
train = fetch_20newsgroups(subset='train')
test = fetch_20newsgroups(subset='test')

# TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(train.data)
X_test = vectorizer.transform(test.data)

# SVM
model = LinearSVC()
model.fit(X_train, train.target)

# Prediction
pred = model.predict(X_test)

# Results
print("SVM Accuracy:", accuracy_score(test.target, pred))
print("\nClassification Report:\n")
print(classification_report(test.target, pred,
                            target_names=test.target_names))